# Generated by Django 3.0.7 on 2020-06-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_auto_20200623_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='AUM',
            field=models.IntegerField(default=1000000),
        ),
    ]
