# Generated by Django 3.0.7 on 2020-06-24 04:05

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_auto_20200623_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='positions',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
