# Generated by Django 3.0.7 on 2020-06-27 19:01

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_auto_20200624_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='positions',
            field=jsonfield.fields.JSONField(default={'name': 'positions'}),
        ),
    ]
