# Generated by Django 3.0.7 on 2020-07-16 05:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_auto_20200627_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='pastReturns',
            field=jsonfield.fields.JSONField(default={'name': 'pastReturns'}),
        ),
    ]
